### ISSUE TITLE
Fail to fetch

### ISSUE THREAD

**Issue by FleurDeLyss** [bar-assistant/docker#1]
Hi, I am using the docker-compose setup but when trying to use the default password or creating a new user, the fetch error show up. 

![2023-01-29 16_05_59-Window](https://user-images.githubusercontent.com/49403276/215355748-5a89a842-51ce-4518-b7af-b6232b1b0259.png)
![2023-01-29 16_07_11-Window](https://user-images.githubusercontent.com/49403276/215355749-46a58d19-6287-4669-94c4-618c4a6e1f06.png)
![2023-01-29 16_07_38-Window](https://user-images.githubusercontent.com/49403276/215355752-5d6d8b8a-dda8-4123-9a00-96b376231b4c.png)
![2023-01-29 16_07_53-Window](https://user-images.githubusercontent.com/49403276/215355753-9f6d23d3-5ed1-49a6-9347-c62e98b82196.png)
![2023-01-29 16_08_18-Window](https://user-images.githubusercontent.com/49403276/215355754-ad21152d-a291-44dd-9f2d-380c071ca38e.png)

**Comment by karlomikus** [comment]
Looks like everything is up. Can you access BA server from your browser? If you used default settings this should be at `localhost:8000`
