### ISSUE TITLE
barassistant can't find meilisearch

### ISSUE THREAD

**Issue by mondlichtpierrot** [bar-assistant/docker#4]
* [x]  I have read [the FAQ](https://bar-assistant.github.io/docs/faq/).

**Describe the bug** After running the Docker Containers like it is mentioned in the Documentation it starts all the containers but the page just stays blank (or Gray)

**Versions:**
* Docker: Docker version 20.10.17
* Browser: Chrome, Firefox

I've been running a `docker compose up -d` as instructed in the readme. No adjustments to the files. The problem is that the login page states: 

> Bar Assistant server:
> http://localhost:3000/bar
> Status: Not available

The logs say

> 
> docker-master-bar-assistant-1  | In Client.php line 170: 
> docker-master-bar-assistant-1  | 
> docker-master-bar-assistant-1  |   Could not resolve host: meilisearch for "http://meilisearch:7700/indexes/co 
> docker-master-bar-assistant-1  |   cktails/settings". 
> docker-master-bar-assistant-1  | 
> docker-master-bar-assistant-1  | 
> docker-master-bar-assistant-1  | In Psr18Client.php line 135:
> docker-master-bar-assistant-1  | 
> docker-master-bar-assistant-1  |   Could not resolve host: meilisearch for "http://meilisearch:7700/indexes/co 
> docker-master-bar-assistant-1  |   cktails/settings".
> docker-master-bar-assistant-1  | 
> docker-master-bar-assistant-1  | 
> docker-master-bar-assistant-1  | In ErrorChunk.php line 56:
> docker-master-bar-assistant-1  | 
> docker-master-bar-assistant-1  |   Could not resolve host: meilisearch for "http://meilisearch:7700/indexes/co 
> docker-master-bar-assistant-1  |   cktails/settings".
> docker-master-bar-assistant-1  | 
> docker-master-bar-assistant-1  | 
> docker-master-bar-assistant-1  | In CurlResponse.php line 326: 
> docker-master-bar-assistant-1  | 
> docker-master-bar-assistant-1  |   Could not resolve host: meilisearch for "http://meilisearch:7700/indexes/co 
> docker-master-bar-assistant-1  |   cktails/settings".

**Comment by karlomikus** [comment]
Are there any logs from Meilisearch?

```
docker compose logs meilisearch
```

**Comment by superfunk2000** [comment]
I think it's the DB version.
Before I did the the pull, I set the Meilisearch version to 1.1 in docker-compose.yaml (image: getmeili/meilisearch:v1.1), as described in the documentation.

And then I get the following errors:
```
meilisearch_1  | Error: Your database version (1.0.2) is incompatible with your current engine version (1.1.1).
meilisearch_1  | To migrate data between Meilisearch versions, please follow our guide on https://docs.meilisearch.com/learn/update_and_migration/updating.html.
meilisearch_1  | Error: Your database version (1.0.2) is incompatible with your current engine version (1.1.1).
meilisearch_1  | To migrate data between Meilisearch versions, please follow our guide on https://docs.meilisearch.com/learn/update_and_migration/updating.html.
meilisearch_1  | Error: Your database version (1.0.2) is incompatible with your current engine version (1.1.1).
meilisearch_1  | To migrate data between Meilisearch versions, please follow our guide on https://docs.meilisearch.com/learn/update_and_migration/updating.html.
meilisearch_1  | Error: Your database version (1.0.2) is incompatible with your current engine version (1.1.1).
meilisearch_1  | To migrate data between Meilisearch versions, please follow our guide on https://docs.meilisearch.com/learn/update_and_migration/updating.html.
meilisearch_1  | Error: Your database version (1.0.2) is incompatible with your current engine version (1.1.1).
meilisearch_1  | To migrate data between Meilisearch versions, please follow our guide on https://docs.meilisearch.com/learn/update_and_migration/updating.html.
meilisearch_1  | Error: Your database version (1.0.2) is incompatible with your current engine version (1.1.1).
meilisearch_1  | To migrate data between Meilisearch versions, please follow our guide on https://docs.meilisearch.com/learn/update_and_migration/updating.html.
meilisearch_1  | Error: Your database version (1.0.2) is incompatible with your current engine version (1.1.1).
meilisearch_1  | To migrate data between Meilisearch versions, please follow our guide on https://docs.meilisearch.com/learn/update_and_migration/updating.html.
meilisearch_1  | Error: Your database version (1.0.2) is incompatible with your current engine version (1.1.1).
meilisearch_1  | To migrate data between Meilisearch versions, please follow our guide on https://docs.meilisearch.com/learn/update_and_migration/updating.html.
```
Then I reset the Meilisearch version to 1.0 and imported a backup of the ./data directory. Now comes after the login attempt "Server Error"

![image](https://github.com/bar-assistant/docker/assets/90634124/c8bb763d-3028-4eff-b4e5-9b89269cab9d)

**Comment by karlomikus** [comment]
You should see more detailed error message in your BA logs.

As for Meilisearch, to update you can just [delete the old instance and volume and pull the new one](https://bar-assistant.github.io/docs/faq/#how-do-i-update-meilisearch).

**Comment by superfunk2000** [comment]
Made a dump, deleted /data, switched to meiliserach 1.1, pull and started the container. Unfortunately doesn't work.
```
bar-assistant    | mkdir: cannot create directory '/var/www/cocktails/storage/bar-assistant/uploads': Permission denied
```

**Comment by zhdenny** [comment]
Permission denied sounds like a permissions issue. You sure ALL related director's are 33:33?

Chown 33:33 /path/to/directory -R

**Comment by superfunk2000** [comment]
OK, that's it of course.
Then I imported the DB dump, but had to register again because my login data was no longer recognized.

Now all my own cocktails and ingredients are gone. My shelves are empty too. :(

Isn't there any chance to get the data back. I made a dump earlier...

**Comment by zhdenny** [comment]
Your own cocktails/ingredients are/were stored in Bar-Assistant Appdata, not Meilisearch Appdata.

When you did your Meilisearch upgrade, you should have only deleted the Meilisearch Appdata.

**Comment by karlomikus** [comment]
I don't think I understand what were you trying to do. When you say "Then I imported the DB dump", what do you mean by that.

If you wanted to update Meilisearch to 1.1, that involves just deleting Meilisearch container with it's volume.

**Comment by zhdenny** [comment]
While upgrading Meilisearch I fear he may have deleted more than just Meilisearch volume/Appdata. Just my guess

**Comment by mondlichtpierrot** [comment]
Hi all,

wow, thanks for all the swift feedback and lively support! In fact, as @superfunk2000 indicated, my original issue seemed to have been wrt the Melisearch version. I think this was because the [docker-compose](https://github.com/bar-assistant/docker/commit/67b81a667e7aed26460e2da1a27ffbe76f4ef3d3) file (until recently) still featured Melisearch 1.0 whereas the [docs](https://bar-assistant.github.io/docs/setup/) proposed using version 1.1 before already, and I might have tried deploying as described there before. 

Anyway, my original issue seems solved so closing this, but feel free to re-open for the discussion that followed. Thanks y'all!
