### ISSUE TITLE
Cannot find meilisearch

### ISSUE THREAD

**Issue by MazenS** [bar-assistant/docker#6]
Ello everyone, 

I'm having a bit of trouble getting this to work.
I did check out the other similarly named thread but couldn't see or understand anything that would be relevant to me.

I followed the instructions on https://docs.barassistant.app/setup/

I created the .env file and modified it with a new MEILI_MASTER_KEY and BASE_URL.
The docker-compose was edited so I'd be using port 3123:3000, everything else was left as default in the nginx.conf.

Using the docker command the containers are created correctly, but I cannot log in - Status: Unavailable .

When I check the logs I see 
```
In Client.php line 159:
  Could not resolve host: meilisearch for "http://meilisearch:7700/indexes/co  
  cktails/documents".                                                          
In Psr18Client.php line 113:
  Could not resolve host: meilisearch for "http://meilisearch:7700/indexes/co  
  cktails/documents".
In ErrorChunk.php line 55:
  Could not resolve host: meilisearch for "http://meilisearch:7700/indexes/co  
  cktails/documents".
In CurlResponse.php line 319:
  Could not resolve host: meilisearch for "http://meilisearch:7700/indexes/co  
  cktails/documents".
```

In the nginx.conf file should I have updated the proxypass with the new BASE_URL I'm using?
Is there something else I should have changed somewhere due to changing the port to 3123 or the BASE_URL to XXX.XXX.X.XXX:3123 ?

Any advice would be grand thanks

**Comment by karlomikus** [comment]
Changing only the base url in env should be enough. But this looks like api cannot communicate with meilisearch. Did you rename some of the containers? Also check that all of them are running.

**Comment by MazenS** [comment]
I never renamed the containers but this is how they are named and defo running.
When I get in I'll double check the compose files to make sure I didn't inadvertently mess things up.

![image](https://github.com/user-attachments/assets/85f51d8f-c094-43b3-865c-09551b106656)

**Comment by MazenS** [comment]
Ok so I grabbed the latest version of the compose yml - I noticed its using a different version of meillisearch.

![image](https://github.com/user-attachments/assets/a7c64049-a4a8-485c-8d6f-0eb260407b25)

I'm still seeing the same issue.
Would it be worth me posting my config files or some other logs?

**Comment by karlomikus** [comment]
Those warnings about empty variables should not be there. Are you sure your .env file exists?
