### ISSUE TITLE
Could not resolve host: meilisearch

### ISSUE THREAD

**Issue by F1zzyD** [bar-assistant/docker#9]
Cannot run service. Always amounting to `Could not resolve host: meilisearch for "http://meilisearch:7700/keys/"`. The readme.md does not state where this service pulls .env either... very confusing instructions....

**Comment by karlomikus** [comment]
Hello, you can check [full docs here](https://docs.barassistant.app/setup/).

I'm guessing this message comes from api container so it could be a few issues. Did you rename the container service, is the meilisearch service running, etc...

Post your setup details, like your compose file for more information.
